<html>
<head>
    <title>Ознакомление с классом String</title>
    <style>
		img{
			max-width: 99%;
		}
		body{
			max-width:99%;
		}
		@font-face{
			font-family: "secon";
			src: url("secon.ttf");
		}
		h1,h2,p{
			font-family:"secon";
		}
    </style>
</head>
<body>
	<h1>try и catch</h1>
	<p>
		Метод производит обработку исключения при использовании ключевых слов try и catch.
	</p>
	<h2>Описание</h2>
	<p>
		Блок try/catch размещается в начале и конце кода, который может сгенерировать исключение. Код в составе блока try/catch является защищенным кодом, синтаксис использования try/catch выглядит следующим образом:
	</p>
	<div><img src="1.jpg"></div>
	<p>
		Код, предрасположенный к исключениям, размещается в блоке try. В случае возникновения исключения, обработка данного исключения будет производиться соответствующим блоком catch. За каждым блоком try должен немедленно следовать блок catch либо блок finally.
		<br><br>Оператор catch включает объявление типа исключения, которое предстоит обработать. При возникновении исключения в защищенном коде, блок catch (либо блоки), следующий за try, будет проверен. В случае, если тип произошедшего исключения представлен в блоке catch, исключение передается в блок catch аналогично тому, как аргумент передается в параметр метода.
	</p>
	<h2>Пример</h2>
	<p>
		Ниже представлен массив с заявленными двумя элементами. Попытка кода получить доступ к третьему элементу массива повлечет за собой генерацию исключения.
	</p>
	<div>
		<img src="2.jpg">
	</div>
	<p>
		Вследствие этого будет получен следующий результат:
		<br>Исключение:java.lang.ArrayIndexOutOfBoundsException: 3
		<br>Вне блока
	</p>
	<h1>Многократные блоки catch</h1>
	<p>
		За блоком try могут следовать несколько блоков catch. Синтаксис многократных блоков catch выглядит следующим образом:
	</p>
	<div>
		<img src="3.jpg">
	</div>
	<p>
		Представленные выше операторы демонстрируют три блока catch, однако, после однократного try количество данных используемых блоков может быть произвольным. В случае возникновения исключения в защищенном коде, исключение выводится в первый блок catch в списке. Если тип данных генерируемого исключения совпадает с ИсключениеТип1, он перехватывается в указанной области. В обратном случае, исключение переходит ко второму оператору catch. Это продолжается до тех пор, пока не будет произведен перехват исключения, либо оно не пройдет через все операторы, в случае чего выполнение текущего метода будет прекращено, и исключение будет перенесено к предшествующему методу в стеке вызовов.
	</p>
	<h2>Пример</h2>
	<p>
		Далее представлен сегмент кода, демонстрирующий использование многократных операторов try/catch.
	</p>
	<div>
		<img src="4.jpg">
	</div>
	<h1>Перехват многотипных исключений</h1>
	<p>
		В среде Java 7, Вы можете произвести обработку более чем одного исключения при использовании одного блока catch, данное свойство упрощает код. Ниже представлена модель реализации:
	</p>
	<div>
		<img src="5.jpg">
	</div>
	<h1>Ключевые слова throws/throw</h1>
	<p>
		В случае если метод не может осуществить обработку контролируемого исключения, производится соответствующее уведомление при использовании ключевого слова throws в Java. Ключевое слово throws появляется в конце сигнатуры метода.
		<br><br>При использовании ключевого слова throw вы можете произвести обработку вновь выявленного исключения либо исключения, которое было только что перехвачено.
		<br><br>Следует внимательно различать ключевые слова throw и throws в Java, так как throws используется для отложенной обработки контролируемого исключения, а throw, в свою очередь, используется для вызова заданного исключения.
		<br><br>Представленный ниже метод отображает, что им генерируется RemoteException:
	</p>
	<h2>Пример 1</h2>
	<div>
		<img src="6.jpg">
	</div>
	<p>
		Метод также может объявить о том, что им генерируется более чем одно исключение, в случае чего исключения представляются в виде перечня, отделенные друг от друга запятыми. К примеру, следующий метод оповещает о том, что им генерируются RemoteException и InsufficientFundsException:
	</p>
	<h2>Пример 2</h2>
	<div>
		<img src="7.jpg">
	</div>
	<h1>Блок finally</h1>
	<p>
		В Java finally следует за блоком try либо блоком catch. Блок finally в коде выполняется всегда независимо от наличия исключения.
		<br><br>Использование блока finally позволяет запустить какой-либо оператор, предназначенный для очистки, не зависимо от того, что происходит в защищенном коде.
		<br><br>Блок finally в Java появляется по окончании блоков catch, его синтаксис выглядит следующим образом:
	</p>
	<h2>Синтаксис</h2>
	<div>
		<img src="8.jpg">
	</div>
	<h2>Пример</h2>
	<div>
		<img src="9.jpg">
	</div>
	<p>
		Вследствие этого будет получен следующий результат:
		<br>Исключение:java.lang.ArrayIndexOutOfBoundsException: 3
		<br>Значение первого элемента: 6
		<br>Оператор finally выполнен.
	</p>
	<p>
		Следует помнить, что:
		<br>• Выражение catch не может существовать без оператора try.
		<br>• При наличии блока try/catch, выражение finally не является обязательным.
		<br>• Блок try не может существовать при отсутствии выражения catch либо выражения finally.
		<br>• Существование какого-либо кода в промежутке между блоками try, catch, finally является невозможным.
	</p>
	<h1>Конструкция try-with-resources</h1>
	<p>
		В норме, при использовании различных видов ресурсов, таких как потоки, соединения и др., нам предстоит закрыть их непосредственно при использовании блока finally. В программе, представленной ниже, нами производится считывание данных из файла при использовании FileReader, после чего он закрывается блоком finally.
	</p>
	<h2>Пример 1</h2>
	<div>
		<img src="10.jpg">
	</div>
	<p>
		Конструкция try-with-resources, также именуемая как автоматическое управление ресурсами, представляет новый механизм обработки исключений, который был представлен в 7-ой версии Java, осуществляя автоматическое закрытие всех ресурсов, используемых в рамках блока try catch.
		<br><br>Чтобы воспользоваться данным оператором, вам всего лишь нужно разместить заданные ресурсы в круглых скобках, после чего созданный ресурс будет автоматически закрыт по окончании блока. Ниже представлен синтаксис конструкции try-with-resources.
	</p>
	<h2>Синтаксис</h2>
	<div>
		<img src="11.jpg">
	</div>
	<p>Программа ниже производит считывание данных в файле, используя конструкцию try-with-resources.</p>
	<h2>Пример 2</h2>
	<div>
		<img src="12.jpg">
	</div>
	<p>
		При работе с конструкцией try-with-resources следует принимать во внимание следующие нюансы:
		<br>• С целью использования конструкции try-with-resources следует реализовать интерфейс AutoCloseable, после чего соответствующий метод close() будет вызван автоматически во время выполнения.
		<br>• В конструкции try-with-resources возможно указание одного и более классов.
		<br>• При указании нескольких классов в блоке try конструкции try-with-resources, закрытие данных классов будет производиться в обратном порядке.
		<br>• За исключением внесения ресурсов в скобки, все элементы являются равными аналогично нормальному блоку try/catch в составе блока try.
		<br>• Ресурсы, внесенные в try, конкретизируются до запуска блока try.
		<br>• Ресурсы непосредственно в составе блока try указываются как окончательные.
	</p>
</body>
</html>